// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhqNQ5ptwvFPNsnjWY8s3r8Qh_2qRW4wQ',
    appId: '1:469444150518:web:0a1a174b614109d96e18d7',
    messagingSenderId: '469444150518',
    projectId: 'proyecto2-25005',
    authDomain: 'proyecto2-25005.firebaseapp.com',
    storageBucket: 'proyecto2-25005.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmMEEA43r5eEOYhRHD8_9HJKHTmike2iA',
    appId: '1:469444150518:android:f67fcd8a222103706e18d7',
    messagingSenderId: '469444150518',
    projectId: 'proyecto2-25005',
    storageBucket: 'proyecto2-25005.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXUXBFSyH2n9pY59z1AqQPMyekyq1JU_8',
    appId: '1:469444150518:ios:c88c9d8e018b6e646e18d7',
    messagingSenderId: '469444150518',
    projectId: 'proyecto2-25005',
    storageBucket: 'proyecto2-25005.appspot.com',
    iosClientId: '469444150518-ra80sdmba7t7l0f41j7r9j0rvk56qrf8.apps.googleusercontent.com',
    iosBundleId: 'com.example.damU4Proyecto219400618',
  );
}
